version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
    command: python /code/backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - migration
  migration:
    build: .
    command: python /code/backend/manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
  serve:
    build: .
    command: python /code/serve/serve.py
    depends_on:
      - backend
    ports:
      - 3000:3000
volumes:
  postgres_data: