# Generated by Django 2.1.5 on 2019-03-04 12:22

import csv
import os
from django.db import migrations
from django.conf import settings
import logging

"""
Inserting ship data defined in the pdf
Importing all the point data from the csv
"""
logger = logging.getLogger(__name__)


def saveShips(apps, schema_editor):
    ships = apps.get_model('restapi', 'ships')
    ships(imo=9632179, name="Mathilde Maersk").save()
    ships(imo=9247455, name="Australian Spirit").save()
    ships(imo=9595321, name="MSC Preziosa").save()


def getCsvData(apps, schema_editor):
    positions = apps.get_model('restapi', 'positions')
    ships = apps.get_model('restapi', 'ships')
    basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # This file contains all the position data change this before migration if necessary
    csvdir = os.path.join(basedir, 'migrations', 'positions.csv')

    with open(csvdir, encoding='UTF-8') as f:
        reader = csv.reader(f)
        for row in reader:
            imo = ships.objects.get(imo=row[0])
            positions(imo=imo,
                      time=row[1],
                      latitude=row[2],
                      longitude=row[3]
                      ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(saveShips),
        migrations.RunPython(getCsvData)
    ]
